---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates on all systems
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
            
- hosts: web_servers
  become: true
  tasks:
          
  - name: install apache2 and php package in Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb in Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba server
    package:
      name: samba
      state: latest



