---

- hosts: all
  become: true
  pre_tasks:
  
  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root

  - name: add ssh key for simone
    tags: always
    authorized_key:
            user: simone
            key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFlZJ8HbAQUHAfoHSjUeul3bPuH9a2EKT7bfgPOrmgSf ansible"

  - name: add suers file for simone
    tags: always
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440
